<?php

/**
 * @file
 * Configuration system that lets administrators modify the workings of the site.
 */

/**
 * The current system version.
 */
define('VERSION', '6.29');

/**
 * Core API compatibility.
 */
define('DRUPAL_CORE_COMPATIBILITY', '6.x');
define('DRUPAL_MINIMUM_PHP',    '4.3.5');
define('DRUPAL_MINIMUM_PHP_MEMORY_LIMIT',    '16M');
define('DRUPAL_MINIMUM_MYSQL',  '4.1.1');
define('DRUPAL_MINIMUM_PGSQL',  '7.4');
define('DRUPAL_MAXIMUM_TEMP_FILE_AGE', 21600);

function system_help($path, $arg) {
  global $base_url;
  switch ($path) {
    case 'admin/help#system':
    case 'admin':
    case 'admin/by-module':
    case 'admin/build/themes':
    case 'admin/build/themes/settings/'. $arg[4]:
    case 'admin/build/themes/settings':
    case 'admin/build/modules':
    case 'admin/build/modules/uninstall':
    case 'admin/build/block/configure':
    case 'admin/settings/actions':
    case 'admin/settings/actions/manage':
    case 'admin/settings/actions/configure':
    case 'admin/reports/status':
      include_once dirname(__FILE__).'/help.inc.php';
      return _real_system_help($path, $arg);
  }
}

function system_theme() {
  include_once dirname(__FILE__).'/theme.inc.php';
  return _real_system_theme();
}

function system_perm() {
  return array('administer site configuration', 'access administration pages', 'administer actions', 'access site reports', 'select different theme', 'administer files');
}

/**
 * Implementation of hook_elements().
 */
function system_elements() {
  // Top level form
  $type['form'] = array('#method' => 'post', '#action' => request_uri());

  // Inputs
  $type['submit'] = array('#input' => TRUE, '#name' => 'op', '#button_type' => 'submit', '#executes_submit_callback' => TRUE, '#process' => array('form_expand_ahah'));
  $type['button'] = array('#input' => TRUE, '#name' => 'op', '#button_type' => 'submit', '#executes_submit_callback' => FALSE, '#process' => array('form_expand_ahah'));
  $type['image_button'] = array('#input' => TRUE, '#button_type' => 'submit', '#executes_submit_callback' => TRUE, '#process' => array('form_expand_ahah'), '#return_value' => TRUE, '#has_garbage_value' => TRUE, '#src' => NULL);
  $type['textfield'] = array('#input' => TRUE, '#size' => 60, '#maxlength' => 128, '#autocomplete_path' => FALSE, '#process' => array('form_expand_ahah'));
  $type['password'] = array('#input' => TRUE, '#size' => 60, '#maxlength' => 128, '#process' => array('form_expand_ahah'));
  $type['password_confirm'] = array('#input' => TRUE, '#process' => array('expand_password_confirm'));
  $type['textarea'] = array('#input' => TRUE, '#cols' => 60, '#rows' => 5, '#resizable' => TRUE, '#process' => array('form_expand_ahah'));
  $type['radios'] = array('#input' => TRUE, '#process' => array('expand_radios'));
  $type['radio'] = array('#input' => TRUE, '#default_value' => NULL, '#process' => array('form_expand_ahah'));
  $type['checkboxes'] = array('#input' => TRUE, '#process' => array('expand_checkboxes'), '#tree' => TRUE);
  $type['checkbox'] = array('#input' => TRUE, '#return_value' => 1, '#process' => array('form_expand_ahah'));
  $type['select'] = array('#input' => TRUE, '#size' => 0, '#multiple' => FALSE, '#process' => array('form_expand_ahah'));
  $type['weight'] = array('#input' => TRUE, '#delta' => 10, '#default_value' => 0, '#process' => array('process_weight', 'form_expand_ahah'));
  $type['date'] = array('#input' => TRUE, '#process' => array('expand_date'), '#element_validate' => array('date_validate'));
  $type['file'] = array('#input' => TRUE, '#size' => 60);

  // Form structure
  $type['item'] = array('#value' => '');
  $type['hidden'] = array('#input' => TRUE, '#process' => array('form_expand_ahah'));
  $type['value'] = array('#input' => TRUE);
  $type['markup'] = array('#prefix' => '', '#suffix' => '');
  $type['fieldset'] = array('#collapsible' => FALSE, '#collapsed' => FALSE, '#value' => NULL, '#process' => array('form_expand_ahah'));
  $type['token'] = array('#input' => TRUE);
  return $type;
}

/**
 * Implementation of hook_menu().
 */
function system_menu() {
  include_once dirname(__FILE__).'/menu.inc.php';
  return _real_system_menu();
}

/**
 * Menu item access callback - only admin or enabled themes can be accessed.
 */
function _system_themes_access($theme) {
  return user_access('administer site configuration') && ($theme->status || $theme->name == variable_get('admin_theme', '0'));
}

/**
 * Implementation of hook_init().
 */
function system_init() {
  // Use the administrative theme if the user is looking at a page in the admin/* path.
  if (arg(0) == 'admin' || (variable_get('node_admin_theme', '0') && arg(0) == 'node' && (arg(1) == 'add' || arg(2) == 'edit'))) {
    global $custom_theme;
    $custom_theme = variable_get('admin_theme', '0');
    drupal_add_css(drupal_get_path('module', 'system') .'/admin.css', 'module');
  }

  // Add the CSS for this module.
  drupal_add_css(drupal_get_path('module', 'system') .'/defaults.css', 'module');
  drupal_add_css(drupal_get_path('module', 'system') .'/system.css', 'module');
  drupal_add_css(drupal_get_path('module', 'system') .'/system-menus.css', 'module');
}

/**
 * Implementation of hook_user().
 *
 * Allows users to individually set their theme and time zone.
 */
function system_user($type, $edit, &$user, $category = NULL) {
  if ($type == 'form' && $category == 'account') {
    $form['theme_select'] = system_theme_select_form(t('Selecting a different theme will change the look and feel of the site.'), isset($edit['theme']) ? $edit['theme'] : NULL, 2);

    if (variable_get('configurable_timezones', 1)) {
      $zones = _system_zonelist();
      $form['timezone'] = array(
        '#type' => 'fieldset',
        '#title' => t('Locale settings'),
        '#weight' => 6,
        '#collapsible' => TRUE,
      );
      $form['timezone']['timezone'] = array(
        '#type' => 'select',
        '#title' => t('Time zone'),
        '#default_value' => strlen($edit['timezone']) ? $edit['timezone'] : variable_get('date_default_timezone', 0),
        '#options' => $zones,
        '#description' => t('Select your current local time. Dates and times throughout this site will be displayed using this time zone.'),
      );
    }

    return $form;
  }
}

function system_block($op = 'list', $delta = 0, $edit = NULL) {
  include_once dirname(__FILE__).'/stock.inc.php';
  return _real_system_block($op, $delta, $edit);
}

function system_admin_menu_block($item) {
  include_once dirname(__FILE__).'/admin.inc.php';
  return _real_system_admin_menu_block($item);
}

function system_admin_theme_submit($form, &$form_state) {
  include_once dirname(__FILE__).'/system.inc.php';
  return _real_system_admin_theme_submit($form, $form_state);
}

function system_theme_select_form($description = '', $default_value = '', $weight = 0) {
  include_once dirname(__FILE__).'/system.inc.php';
  return _real_system_theme_select_form($description, $default_value,
        $weight);
}

function system_check_directory($form_element) {
  include_once dirname(__FILE__).'/system.inc.php';
  return _real_system_check_directory($form_element);
}

function system_get_files_database(&$files, $type) {
  include_once dirname(__FILE__).'/admin.inc.php';
  return _real_system_get_files_database($files, $type);
}

function system_theme_default() {
  include_once dirname(__FILE__).'/admin.inc.php';
  return _real_system_theme_default();
}

function system_theme_data() {
  include_once dirname(__FILE__).'/admin.inc.php';
  return _real_system_theme_data();
}

function _system_theme_data() {
  include_once dirname(__FILE__).'/admin.inc.php';
  return _real__system_theme_data();
}

function system_find_base_themes($themes, $key, $used_keys = array()) {
  include_once dirname(__FILE__).'/admin.inc.php';
  return _real_system_find_base_themes($themes, $key, $used_keys);
}

function system_find_base_theme($themes, $key, $used_keys = array()) {
  include_once dirname(__FILE__).'/admin.inc.php';
  return _real_system_find_base_theme($themes, $key, $used_keys);
}

/**
 * Get a list of available regions from a specified theme.
 *
 * @param $theme_key
 *   The name of a theme.
 * @return
 *   An array of regions in the form $region['name'] = 'description'.
 */
function system_region_list($theme_key) {
  static $list = array();

  if (!array_key_exists($theme_key, $list)) {
    $info = unserialize(db_result(db_query("SELECT info FROM {system} WHERE type = 'theme' AND name = '%s'", $theme_key)));
    $list[$theme_key] = array_map('t', $info['regions']);
  }

  return $list[$theme_key];
}

function system_default_region($theme) {
  $regions = array_keys(system_region_list($theme));
  return isset($regions[0]) ? $regions[0] : '';
}

function system_initialize_theme_blocks($theme) {
  include_once dirname(__FILE__).'/system.inc.php';
  return _real_system_initialize_theme_blocks($theme);
}

function system_settings_form($form) {
  include_once dirname(__FILE__).'/settingsform.inc.php';
  return _real_system_settings_form($form);
}

function system_settings_form_submit($form, &$form_state) {
  include_once dirname(__FILE__).'/settingsform.inc.php';
  return _real_system_settings_form_submit($form, $form_state);
}

function _system_sort_requirements($a, $b) {
  include_once dirname(__FILE__).'/system.inc.php';
  return _real_system_sort_requirements($a, $b);
}

function system_node_type($op, $info) {
  include_once dirname(__FILE__).'/system.inc.php';
  return _real_system_node_type($op, $info);
}

function confirm_form($form, $question, $path, $description = NULL, $yes = NULL, $no = NULL, $name = 'confirm') {
  include_once dirname(__FILE__).'/confirm.inc.php';
  return _real_confirm_form($form, $question, $path, $description,
        $yes, $no, $name);
}

/**
 * Determine if a user is in compact mode.
 */
function system_admin_compact_mode() {
  global $user;
  return (isset($user->admin_compact_mode)) ? $user->admin_compact_mode : variable_get('admin_compact_mode', FALSE);
}

function system_get_module_admin_tasks($module) {
  include_once dirname(__FILE__).'/admin.inc.php';
  return _real_system_get_module_admin_tasks($module);
}

function system_cron() {
  include_once dirname(__FILE__).'/cron.inc.php';
  return _real_system_cron();
}

function system_hook_info() {
  return array(
    'system' => array(
      'cron' => array(
        'run' => array(
          'runs when' => t('When cron runs'),
        ),
      ),
    ),
  );
}

function system_action_info() {
  include_once dirname(__FILE__).'/system.inc.php';
  return _real_system_action_info();
}

function system_actions_manage() {
  include_once dirname(__FILE__).'/actions.inc.php';
  return _real_system_actions_manage();
}

function system_actions_manage_form($form_state, $options = array()) {
  include_once dirname(__FILE__).'/actions.inc.php';
  return _real_system_actions_manage_form($form_state, $options);
}

function system_actions_manage_form_submit($form, &$form_state) {
  include_once dirname(__FILE__).'/actions.inc.php';
  return _real_system_actions_manage_form_submit($form, $form_state);
}

function system_actions_configure($form_state, $action = NULL) {
  include_once dirname(__FILE__).'/actions.inc.php';
  return _real_system_actions_configure($form_state, $action);
}

function system_actions_configure_validate($form, $form_state) {
  include_once dirname(__FILE__).'/actions.inc.php';
  return _real_system_actions_configure_validate($form, $form_state);
}

function system_actions_configure_submit($form, &$form_state) {
  include_once dirname(__FILE__).'/actions.inc.php';
  return _real_system_actions_configure_submit($form, $form_state);
}

function system_actions_delete_form($form_state, $action) { 
  include_once dirname(__FILE__).'/actions.inc.php';
  return _real_system_actions_delete_form($form_state, $action);
}

function system_actions_delete_form_submit($form, &$form_state) {
  include_once dirname(__FILE__).'/actions.inc.php';
  return _real_system_actions_delete_form_submit($form, $form_state);
}

function system_action_delete_orphans_post($orphaned) { 
  include_once dirname(__FILE__).'/actions.inc.php';
  return _real_system_action_delete_orphans_post($orphaned);
}

function system_actions_remove_orphans() { 
  include_once dirname(__FILE__).'/actions.inc.php';
  return _real_system_actions_remove_orphans();
}

function system_send_email_action_form($context) { 
  include_once dirname(__FILE__).'/actions.inc.php';
  return _real_system_send_email_action_form($context);
}

function system_send_email_action_validate($form, $form_state) { 
  include_once dirname(__FILE__).'/actions.inc.php';
  return _real_system_send_email_action_validate($form, $form_state);
}

function system_send_email_action_submit($form, $form_state) { 
  include_once dirname(__FILE__).'/actions.inc.php';
  return _real_system_send_email_action_submit($form, $form_state);
}

function system_send_email_action($object, $context) { 
  include_once dirname(__FILE__).'/actions.inc.php';
  return _real_system_send_email_action($object, $context);
}

function system_mail($key, &$message, $params) {
  include_once dirname(__FILE__).'/mail.inc.php';
  return _real_system_mail($key, $message, $params);
}

function system_message_action_form($context) {
  include_once dirname(__FILE__).'/actions.inc.php';
  return _real_system_message_action_form($context);
}

function system_message_action_submit($form, $form_state) {
  include_once dirname(__FILE__).'/actions.inc.php';
  return _real_system_message_action_submit($form, $form_state);
}

function system_message_action(&$object, $context = array()) {
  include_once dirname(__FILE__).'/actions.inc.php';
  return _real_system_message_action($object, $context);
}

function system_goto_action_form($context) {
  include_once dirname(__FILE__).'/actions.inc.php';
  return _real_system_goto_action_form($context);
}

function system_goto_action_submit($form, $form_state) {
  include_once dirname(__FILE__).'/actions.inc.php';
  return _real_system_goto_action_submit($form, $form_state);
}

function system_goto_action($object, $context) {
  include_once dirname(__FILE__).'/actions.inc.php';
  return _real_system_goto_action($object, $context);
}

function _system_zonelist() {
  include_once dirname(__FILE__).'/system.inc.php';
  return _real_system_zonelist();
}

function system_check_http_request() {
  include_once dirname(__FILE__).'/system.inc.php';
  return _real_system_check_http_request();
}

function theme_system_powered_by($image_path) {
  include_once dirname(__FILE__).'/stock.inc.php';
  return _real_theme_system_powered_by($image_path);
}
